PLAYER_MOVEMENT_SPEED = 10
DASH_BUFF = 5
TILE_SCALING = 0.5
COIN_SCALING = 0.5
SPRITE_PIXEL_SIZE = 128
DASH_DISTANCE = SPRITE_PIXEL_SIZE*TILE_SCALING*3
print(DASH_DISTANCE/(PLAYER_MOVEMENT_SPEED * DASH_BUFF))